version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: recruitment-management-db
    environment:
      POSTGRES_USER: rahim
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: recruitment_management
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recruitment-management-app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: rahim
      DB_PASSWORD: 1234
      DB_NAME: recruitment_management
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
